AllCops:
  Exclude:
    - bin/**

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - spec/**
    - stemmerb.gemspec

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
